[06-Jul-2022 09:50:11 America/Panama] #Exception Method not found: index(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 12:06:40 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, null given(/srv/http/regso/app/controllers/usuario.php): 73
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/usuario.php(73): count
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): cambiar_clave
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(23): call_user_func_array
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 12:23:43 America/Panama] #TypeError date(): Argument #2 ($timestamp) must be of type ?int, string given(/srv/http/regso/app/controllers/auth.php): 33
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/auth.php(33): date
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): procesar_auth
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 12:26:01 America/Panama] #TypeError date(): Argument #2 ($timestamp) must be of type ?int, string given(/srv/http/regso/app/controllers/auth.php): 33
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/auth.php(33): date
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): procesar_auth
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 12:28:28 America/Panama] #TypeError date(): Argument #2 ($timestamp) must be of type ?int, string given(/srv/http/regso/app/controllers/auth.php): 33
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/auth.php(33): date
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): procesar_auth
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/auth.php(33): date()
#1 [internal function]: App\Controllers\Auth->procesar_auth()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 12:30:36 America/Panama] #ArgumentCountError Too few arguments to function App\Controllers\Auth::cambiar_clave(), 0 passed and exactly 1 expected(/srv/http/regso/app/controllers/auth.php): 94
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 (#0 (): cambiar_clave
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
#1 /srv/http/regso/core/router.php(17): call_user_func
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
#2 /srv/http/regso/index.php(9): run
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#3{main})
[06-Jul-2022 12:31:30 America/Panama] #ArgumentCountError Too few arguments to function App\Controllers\Auth::cambiar_clave(), 0 passed and exactly 1 expected(/srv/http/regso/app/controllers/auth.php): 94
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 (#0 (): cambiar_clave
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
#1 /srv/http/regso/core/router.php(17): call_user_func
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
#2 /srv/http/regso/index.php(9): run
	 #0 [internal function]: App\Controllers\Auth->cambiar_clave()
#1 /srv/http/regso/core/router.php(17): call_user_func()
#2 /srv/http/regso/index.php(9): Core\Router::run()
#3 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#3{main})
[06-Jul-2022 13:07:53 America/Panama] #Exception Method not found: index(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 13:10:54 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, null given(/srv/http/regso/app/controllers/usuario.php): 73
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/usuario.php(73): count
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): cambiar_clave
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(23): call_user_func_array
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/usuario.php(73): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:14:44 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, null given(/srv/http/regso/app/controllers/usuario.php): 74
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/usuario.php(74): count
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): cambiar_clave
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(23): call_user_func_array
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:16:35 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, string given(/srv/http/regso/app/controllers/usuario.php): 74
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/usuario.php(74): count
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): cambiar_clave
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(23): call_user_func_array
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/usuario.php(74): count()
#1 [internal function]: App\Controllers\Usuario::cambiar_clave()
#2 /srv/http/regso/core/router.php(23): call_user_func_array()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:30:07 America/Panama] #Exception Method not found: index(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 13:31:08 America/Panama] #Exception Archivo de vista no encontrado admin index(/srv/http/regso/core/engine.php): 39
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/admin.php(16): render
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): index
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:31:49 America/Panama] #Exception Archivo de vista no encontrado admin index(/srv/http/regso/core/engine.php): 39
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/admin.php(16): render
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): index
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:31:53 America/Panama] #Exception Archivo de vista no encontrado admin index(/srv/http/regso/core/engine.php): 39
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 (#0 /srv/http/regso/app/controllers/admin.php(16): render
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#1 (): index
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#2 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
#3 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/app/controllers/admin.php(16): Core\Engine::render()
#1 [internal function]: App\Controllers\Admin->index()
#2 /srv/http/regso/core/router.php(17): call_user_func()
#3 /srv/http/regso/index.php(9): Core\Router::run()
#4 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#4{main})
[06-Jul-2022 13:37:39 America/Panama] #Exception Method not found: index(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 13:42:35 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, string given(/srv/http/regso/app/views/hojas/crear.php): 30
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 (#0 /srv/http/regso/core/engine.php(23): require_once
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#1 /srv/http/regso/app/controllers/hojas.php(37): render
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#2 (): crear
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#3 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#4 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#5{main})
[06-Jul-2022 13:42:37 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, string given(/srv/http/regso/app/views/hojas/crear.php): 30
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 (#0 /srv/http/regso/core/engine.php(23): require_once
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#1 /srv/http/regso/app/controllers/hojas.php(37): render
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#2 (): crear
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#3 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#4 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#5{main})
[06-Jul-2022 13:42:38 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, string given(/srv/http/regso/app/views/hojas/crear.php): 30
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 (#0 /srv/http/regso/core/engine.php(23): require_once
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#1 /srv/http/regso/app/controllers/hojas.php(37): render
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#2 (): crear
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#3 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#4 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#5{main})
[06-Jul-2022 13:42:38 America/Panama] #TypeError count(): Argument #1 ($value) must be of type Countable|array, string given(/srv/http/regso/app/views/hojas/crear.php): 30
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 (#0 /srv/http/regso/core/engine.php(23): require_once
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#1 /srv/http/regso/app/controllers/hojas.php(37): render
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#2 (): crear
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#3 /srv/http/regso/core/router.php(17): call_user_func
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
#4 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/core/engine.php(23): require_once()
#1 /srv/http/regso/app/controllers/hojas.php(37): Core\Engine::render()
#2 [internal function]: App\Controllers\Hojas->crear()
#3 /srv/http/regso/core/router.php(17): call_user_func()
#4 /srv/http/regso/index.php(9): Core\Router::run()
#5 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#5{main})
[06-Jul-2022 13:52:23 America/Panama] #Exception Method not found: guardar_atencion(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 13:54:35 America/Panama] #Exception Method not found: guardar_atencion(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 13:54:36 America/Panama] #Exception Method not found: guardar_atencion(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 14:02:41 America/Panama] #Exception Controller not found: distrito(/srv/http/regso/core/router.php): 29
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 14:04:37 America/Panama] #Exception Controller not found: distrito(/srv/http/regso/core/router.php): 29
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
[06-Jul-2022 15:44:01 America/Panama] PHP Fatal error:  Can't use function return value in write context in /srv/http/regso/app/controllers/atenciones.php on line 55
[06-Jul-2022 16:07:08 America/Panama] #Exception Method not found: index(/srv/http/regso/core/router.php): 19
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 (#0 /srv/http/regso/index.php(9): run
	 #0 /srv/http/regso/index.php(9): Core\Router::run()
#1 {main} 
	 ()
	-------------------------------------------------------------------------------------------------------------------------------#1{main})
